
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.FileChooserUI;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrator
 */
public class Notepad extends javax.swing.JFrame {

    /**
     * Creates new form Notepad
     */
    public Notepad() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

            initComponents();
            setTitle("Untitled-Notepad");
            setBounds(100, 100, 300, 300);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dosyaSecici = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        ekranTA = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMn = new javax.swing.JMenu();
        newMN = new javax.swing.JMenuItem();
        openMn = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        exitMN = new javax.swing.JMenuItem();
        editMn = new javax.swing.JMenu();
        formatMn = new javax.swing.JMenu();
        viewMn = new javax.swing.JMenu();
        helpMn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(ikonCiz());
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        ekranTA.setColumns(20);
        ekranTA.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        ekranTA.setRows(5);
        jScrollPane1.setViewportView(ekranTA);

        getContentPane().add(jScrollPane1);

        fileMn.setText("File");

        newMN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMN.setText("New");
        newMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMNActionPerformed(evt);
            }
        });
        fileMn.add(newMN);

        openMn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMn.setText("Open...");
        openMn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMnActionPerformed(evt);
            }
        });
        fileMn.add(openMn);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        fileMn.add(jMenuItem3);

        jMenuItem4.setText("Save As...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        fileMn.add(jMenuItem4);
        fileMn.add(jSeparator1);

        jMenuItem5.setText("Page Setup...");
        fileMn.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Print...");
        fileMn.add(jMenuItem6);
        fileMn.add(jSeparator2);

        exitMN.setText("Exit");
        exitMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMNActionPerformed(evt);
            }
        });
        fileMn.add(exitMN);

        jMenuBar1.add(fileMn);

        editMn.setText("Edit");
        jMenuBar1.add(editMn);

        formatMn.setText("Format");
        jMenuBar1.add(formatMn);

        viewMn.setText("View");
        jMenuBar1.add(viewMn);

        helpMn.setText("Help");
        jMenuBar1.add(helpMn);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMNActionPerformed

    private void openMnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMnActionPerformed
        try {
            dosyaSecici.showOpenDialog(this);
            File secilenDosya = dosyaSecici.getSelectedFile();
            setTitle(secilenDosya.getName() + "-Notepad");
            Scanner sc = new Scanner(secilenDosya);
            while (sc.hasNextLine()) {
                ekranTA.append(sc.nextLine() + "\n");
            }
        } catch (FileNotFoundException ex) {
        }

    }//GEN-LAST:event_openMnActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        JFileChooser frm = new JFileChooser();
        frm.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        frm.showOpenDialog(frm);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void newMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMNActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Do you want save the changes", "Notepad", JOptionPane.YES_NO_CANCEL_OPTION);
        
    }//GEN-LAST:event_newMNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notepad().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser dosyaSecici;
    private javax.swing.JMenu editMn;
    private javax.swing.JTextArea ekranTA;
    private javax.swing.JMenuItem exitMN;
    private javax.swing.JMenu fileMn;
    private javax.swing.JMenu formatMn;
    private javax.swing.JMenu helpMn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem newMN;
    private javax.swing.JMenuItem openMn;
    private javax.swing.JMenu viewMn;
    // End of variables declaration//GEN-END:variables

    private Image ikonCiz() {
       return  Toolkit.getDefaultToolkit().createImage("D:\\javaEylul2013\\notepad.png");
      
    }
}
